[theme]
base = "light"
primaryColor = "#03045e"
backgroundColor = "#F1F4FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#03045e"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
